### PR TITLE
Closes #22 Implemented the endpoint answer/all/{questionId} 

### LINKED ISSUE #22: Implement the endpoint  answer/all/{questionId} to get all answers to a particular question.
This endpoint is used to get all answers to a particular question. Any user can access this endpoint.

- [ ] It should be a GET request.

- [ ] This endpoint requests the path variable 'questionId' as a string for the corresponding question whose answers are to be retrieved from the database and access token of the signed in user as a string in authorization Request Header.

- [ ] If the access token provided by the user does not exist in the database throw "AuthorizationFailedException" with the message code - 'ATHR-001' and message - 'User has not signed in'.

- [ ] If the user has signed out, throw "AuthorizationFailedException" with the message code - 'ATHR-002' and message - 'User is signed out.Sign in first to get the answers'.

- [ ] If the question with uuid whose answers are to be retrieved from the database does not exist in the database, throw "InvalidQuestionException" with the message code - 'QUES-001' and message - 'The question with entered uuid whose details are to be seen does not exist'.

- [ ] Else, return "uuid" of the answer, "content" of the question and "content" of all the answers posted for that particular question from the database in the JSON response with the corresponding HTTP status.

- [ ] Fix test cases if any.

### PR DESCRIPTION
**Pull request by Madhan-Kumar-Gali**
i have implemented the  endpoint answer/all/{questionId}  inside the answer-api branch now all of you can verify it.

### CODE REVIEW

File: quora-service/src/main/java/com/upgrad/quora/service/entity/AnswerEntity.java [hunk 1]
```diff
@@ -15,7 +15,8 @@
 @Entity
 @Table(name = "answer")
 @NamedQueries({
-        @NamedQuery(name = "getAnswerById", query = "select a from AnswerEntity a where a.uuid=:uuid")
+        @NamedQuery(name = "getAnswerById", query = "select a from AnswerEntity a where a.uuid=:uuid"),
+        @NamedQuery(name = "getAllAnswersToQuestion", query = "select a from AnswerEntity a")
```
Comment (smeeth-virpariya) [inline quora-service/src/main/java/com/upgrad/quora/service/entity/AnswerEntity.java]: You are basically getting all the answers irrespective of question. 
Please add where clause to complete this.

Comment (Madhan-Kumar-Gali) [reply quora-service/src/main/java/com/upgrad/quora/service/entity/AnswerEntity.java]: ok
